### ISSUE TITLE
Add Clock Time stamps to gifs

### ISSUE THREAD

**Issue by jalpp** [lichess-org/lila-gif#107]
Lichess gifs are a great way to show games, but having a clock time stamp can be helpful to provide more insights into the game, for example, if the player lost on time, or they blundered a piece because of time pressure.

**Comment by niklasf** [comment]
One potential issue: Users might expect a running clock, which would add many many frames.

**Comment by jalpp** [comment]
Yeah true, maybe adding time stamp for every 4 or 5 moves can reduce the frames and add a clock to the gif.
