### ISSUE TITLE
Show coordinates

### ISSUE THREAD

**Issue by niklasf** [lichess-org/lila-gif#128]
Like the "inside the board" style on Lichess.

**Comment by cymruu** [comment]
I just realized it wasn't antyaliasing issue. Here are the updated version screenshots

```http://127.0.0.1:6175/image.gif?fen=4k3/6KP/8/8/8/8/7p/8&orientation=black&lastMove=a1a2```
![image](https://user-images.githubusercontent.com/2981598/208441855-5ce812fc-d069-4497-a76b-69227706ffbd.png)

```http://127.0.0.1:6175/image.gif?fen=4k3/6KP/8/8/8/8/7p/8&lastMove=h1h2```
![image](https://user-images.githubusercontent.com/2981598/208441931-3bd9f5f9-4643-416a-8cbd-3ceb47e21185.png)

https://github.com/cymruu/lila-gif/blob/c5fd03d08fe448eafc5da2baf8c9b3b782a2a247/example.gif?raw=true

**Comment by benediktwerner** [comment]
nice. still a bit hard to read with the grey color. but do you want to create a draft PR? would make a bit more sense to discuss stuff like this there than on the issue.
